Update maven-build.yml

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -23,8 +23,8 @@ jobs:
     strategy:
       matrix:
         java: [ '17' ]
-    outputs:
-      my_output: ${{ steps.sbom_attest.outputs.result }}
+    # outputs:
+      # my_output: ${{ steps.generate_sbom.outputs.result }}
 
     steps:
       - uses: actions/checkout@v4
@@ -109,22 +109,22 @@ jobs:
           curl -sSL https://github.com/anchore/syft/releases/download/v0.66.0/syft_0.66.0_linux_amd64.tar.gz | tar xz -C /usr/local/bin syft
 
       - name: Generate SBOM with Syft
-        id: sbom_attest
+        # id: generate_sbom
         run: |
-          echo "result=`syft dir:. -o cyclonedx-json > sbom.json`" >> $GITHUB_ENV
-          ls
-
-      - name: Generate SBOM attestation
-        uses: actions/attest-sbom@v1
-        with:
-          subject-path: ./sbom.json
-          sbom-path: ./sbom.json
+          # echo "result=`syft dir:. -o cyclonedx-json > sbom.json`" >> $GITHUB_ENV
+          syft dir:. -o cyclonedx-json > sbom.json
 
       - name: Upload SBOM
         uses: actions/upload-artifact@v4
         with:
           name: sbom
           path: sbom.json
+
+      - name: Generate SBOM attestation
+        uses: actions/attest-sbom@v1
+        with:
+          subject-path: ./sbom.json
+          sbom-path: ./sbom.json
 
       - name: verify SBOM attesttion
         env:
@@ -204,6 +204,11 @@ jobs:
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
+
+      - name: Download file artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: sbom
         
       - name: Log in to GitHub Container Registry
         uses: docker/login-action@v2
@@ -265,11 +270,12 @@ jobs:
           set -e  # Exit on error
 
           # Run the cosign attach sbom command and capture its output
-          echo "sbom: ${{ needs.build.outputs.my_output }}"
-          output=$(cosign attach sbom --sbom ${{ needs.build.outputs.my_output }} ghcr.io/saurav631/spring-petclinic:latest) || { echo "Failed to run cosign attach sbom"; exit 1; }
+          # echo "sbom: ${{ needs.build.outputs.my_output }}"
+          # output=$(cosign attach sbom --sbom ${{ needs.build.outputs.my_output }} ghcr.io/saurav631/spring-petclinic:latest) || { echo "Failed to run cosign attach sbom"; exit 1; }
+          output=$(cosign attach sbom --sbom sbom.json ghcr.io/saurav631/spring-petclinic:latest) || { echo "Failed to run cosign attach sbom"; exit 1; }
           # output=$(cosign attach sbom --sbom sbom.json ghcr.io/saurav631/spring-petclinic:latest) || { echo "Failed to run cosign attach sbom"; exit 1; }
           # cosign attest --predicate <FILE> --type <TYPE> --key cosign.key <IMAGE>
-          # echo "$output"
+          echo "output: $output"
           
           # Extract the SHA from the output
           sbom_filename=$(echo "$output" | grep -oP 'sha256-[\w\d]+\.sbom') || { echo "Failed to extract SBOM filename"; exit 1; }
