Update maven-build.yml

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -381,17 +381,53 @@ jobs:
         with:
           name: git-details
           path: output.json
+            
+  last_job:
+    permissions:
+      security-events: write
+      id-token: write
+      contents: read
+      attestations: write
+      packages: write
+    runs-on: ubuntu-latest
+    # strategy:
+    #   matrix:
+    #     java: [ '17' ]
+
+    steps:
+      - name: Check Out Source Code
+        uses: actions/checkout@v3
+
+      - name: Download output.json file artifact
+        uses: actions/download-artifact@v3
+        with:
+          name: git-details
+
+      - name: Log in to GitHub Container Registry
+        uses: docker/login-action@v2
+        with:
+          username: ${{github.actor}}
+          password: ${{secrets.GH_TOKEN}}
+          registry: ghcr.io
+
+      - name: Public Key Creation
+        run: |
+          cosign public-key --key env://COSIGN_KEY > cosign.pub
+        shell: bash
+        env:
+          COSIGN_KEY: ${{secrets.Cosign_Key}}
+          COSIGN_PASSWORD: ${{secrets.Cosign_Key_Password}}
 
       - name: Attestation using Predicate
         run: |
-          # $(cosign attest --key env://COSIGN_KEY1 --predicate output.json ghcr.io/saurav631/spring-petclinic:latest --yes 2>&1) || { echo "Failed to attest predicate with the image"; exit 1; }
-          $(cat output.json | cosign attest --predicate - ghcr.io/saurav631/spring-petclinic:latest --yes 2>&1) || { echo "Failed to attest predicate with the image"; exit 1; }
-        # shell: bash
-        # env:
-          # COSIGN_KEY1: ${{secrets.Cosign_Key}}
-          # COSIGN_PASSWORD: ${{secrets.Cosign_Key_Password}}
+          cosign attest --key env://COSIGN_KEY --predicate output.json ghcr.io/saurav631/spring-petclinic:latest --yes
+          # $(cosign attest --key env://COSIGN_KEY --predicate output.json ghcr.io/saurav631/spring-petclinic:latest --yes 2>&1) || { echo "Failed to attest predicate with the image"; exit 1; }
+          # $(cat output.json | cosign attest --predicate - ghcr.io/saurav631/spring-petclinic:latest --yes 2>&1) || { echo "Failed to attest predicate with the image"; exit 1; }
+        shell: bash
+        env:
+          COSIGN_KEY: ${{secrets.Cosign_Key}}
+          COSIGN_PASSWORD: ${{secrets.Cosign_Key_Password}}
 
       - name: Verify Predicate Attestation
         run: |
           $(cosign verify-attestation --key cosign.pub ghcr.io/saurav631/spring-petclinic:latest 2>&1) || { echo "Failed to verify the attested image"; exit 1; }
-            
