Update maven-build.yml

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -345,14 +345,21 @@ jobs:
 
       - name: upload SBOM to Github Registry
         run: |
-          set -e  # Exit on error
+          # set -e  # Exit on error
           output2=$(cosign upload blob -f sbom.json ghcr.io/saurav631/demo/sbom.json | jq . 2>&1) || { echo "Failed to upload the blob to the Registry"; exit 1; }
           echo "output: $output2"
+          sbom_file=$(echo "$output2" | grep -oP 'sha256-[\w\d]+') || { echo "Failed to extract SBOM filename"; exit 1; }
+          # Set the extracted SHA as an environment variable
+          echo "SBOM_FILE=$sbom_file" >> $GITHUB_ENV
 
       # - name: Download SBOM Digest Locally
       #   run: |
-      #     set -e  # Exit on error
-      #     curl -L gcr.io/v2/user/demo/artifact/blobs
+      #     # set -e  # Exit on error
+      #     curl -L ghcr.io/saurav631/demo/sbom.json/blobs/$SBOM_FILE
+
+      - name: Sign SBOM
+        run: |
+          cosign sign --yes --key env://COSIGN_KEY ghcr.io/saurav631/demo/sbom.json/$SBOM_FILE
 
       - name: Fetch commit details
         run: |
