Update maven-build.yml

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -348,7 +348,7 @@ jobs:
           # set -e  # Exit on error
           output2=$(cosign upload blob -f cosign.bundle ghcr.io/saurav631/spring-petclinic:latest 2>&1) #| jq .) #|| { echo "Failed to upload the blob to the Registry"; exit 1; }
           echo "output: $output2"
-          sbom_file=$(echo "$output2" | grep -oP 'sha256:[\w\d]{64}' | head -n 2) || { echo "Failed to extract SBOM filename"; exit 1; }
+          sbom_file=$(echo "$output2" | grep -oP 'sha256:[\w\d]{64}' | head -n 1) || { echo "Failed to extract SBOM filename"; exit 1; }
           echo "sbom_file: $sbom_file"
           # Set the extracted SHA as an environment variable
           # echo "SBOM_FILE=$sbom_file" >> $GITHUB_ENV
@@ -358,13 +358,13 @@ jobs:
       #     # set -e  # Exit on error
       #     curl -L ghcr.io/saurav631/demo/sbom.json/blobs/$SBOM_FILE
 
-      - name: Sign SBOM
+      - name: Verify SBOM Uploaded to Image Repo
         run: |
-          cosign sign --yes --key env://COSIGN_KEY ghcr.io/saurav631/spring-petclinic/$SBOM_FILE
-        shell: bash
-        env:
-          COSIGN_KEY: ${{secrets.Cosign_Key}}
-          COSIGN_PASSWORD: ${{secrets.Cosign_Key_Password}}
+          cosign verify --certificate-github-workflow-name=.github/workflows/maven-build.yml@refs/heads/main --certificate-github-workflow-ref=refs/heads/main --certificate-github-workflow-repository=https://github.com/saurav631/spring-petclinic --certificate-github-workflow-trigger=workflow_dispatch --key cosign.pub ghcr.io/saurav631/spring-petclinic/$SBOM_FILE | jq -r .payload | base64 --decode | jq .
+        # shell: bash
+        # env:
+        #   COSIGN_KEY: ${{secrets.Cosign_Key}}
+        #   COSIGN_PASSWORD: ${{secrets.Cosign_Key_Password}}
 
       - name: Fetch commit details
         run: |
