Update maven-build.yml

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -17,6 +17,7 @@ jobs:
       id-token: write
       contents: read
       attestations: write
+      packages: write
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -36,46 +37,51 @@ jobs:
         run: |
           pwd
           ./mvnw -B package > app.jar
+          ls
+      # - uses: actions/checkout@v4
+      #   with:
+      #     fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
 
       - name: Generate artifact attestation
         uses: actions/attest-build-provenance@v1
         with:
           subject-path: ./app.jar
-
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
-      - name: Set up JDK 17
-        uses: actions/setup-java@v1
-        with:
-          java-version: 17
-      - name: Cache SonarQube packages
-        uses: actions/cache@v1
-        with:
-          path: ~/.sonar/cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
-      - name: Cache Maven packages
-        uses: actions/cache@v1
-        with:
-          path: ~/.m2
-          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
-          restore-keys: ${{ runner.os }}-m2
-      - name: Build and analyze
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-          SONAR_HOST_URL: http://20.235.200.36:9000/
-        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=PetClinic -Dsonar.projectName='PetClinic'
+          
+      # - name: Set up JDK 17
+      #   uses: actions/setup-java@v1
+      #   with:
+      #     java-version: 17
+          
+      # - name: Cache SonarQube packages
+      #   uses: actions/cache@v1
+      #   with:
+      #     path: ~/.sonar/cache
+      #     key: ${{ runner.os }}-sonar
+      #     restore-keys: ${{ runner.os }}-sonar
+          
+      # - name: Cache Maven packages
+      #   uses: actions/cache@v1
+      #   with:
+      #     path: ~/.m2
+      #     key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
+      #     restore-keys: ${{ runner.os }}-m2
+          
+      # - name: Build and analyze
+      #   env:
+      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      #     SONAR_HOST_URL: http://20.235.200.36:9000/
+      #   run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=PetClinic -Dsonar.projectName='PetClinic'
       
-      - name: Check SonarQube Quality Gate
-        run: |
-         sleep 10
-          STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }} "http://20.235.200.36:9000/api/qualitygates/project_status?projectKey=PetClinic" | jq -r '.projectStatus.status')
-          echo "Quality Gate Status: $STATUS"
-          if [ "$STATUS" != "OK" ]; then
-            echo "SonarQube Quality Gate failed"
-            exit 1
-          fi      
+      # - name: Check SonarQube Quality Gate
+      #   run: |
+      #    sleep 10
+      #     STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }} "http://20.235.200.36:9000/api/qualitygates/project_status?projectKey=PetClinic" | jq -r '.projectStatus.status')
+      #     echo "Quality Gate Status: $STATUS"
+      #     if [ "$STATUS" != "OK" ]; then
+      #       echo "SonarQube Quality Gate failed"
+      #       exit 1
+      #     fi  
+          
       - name: Install & Running TruffleHog
         run: |
           pip install truffleHog
@@ -88,6 +94,12 @@ jobs:
       - name: Generate SBOM with Syft
         run: |
           syft dir:. -o cyclonedx-json > sbom.json
+
+      - name: Generate SBOM attestation
+        uses: actions/attest-sbom@v1
+        with:
+          subject-path: ./app.jar
+          sbom-path: ./sbom.json
 
       - name: Upload SBOM
         uses: actions/upload-artifact@v3
