Update maven-build.yml

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -329,6 +329,20 @@ jobs:
           output1=$(cosign verify-attestation --key cosign.pub ghcr.io/saurav631/spring-petclinic:latest | jq . 2>&1) || { echo "Failed to verify the attested image"; exit 1; }
           echo "output: $output1"
 
+      - name: Sign SBOM
+        run: |
+          set -e  # Exit on error
+          (cosign sign-blob --key cosign.key sbom.json | jq -r .payload | base64 --decode | jq . 2>&1) || { echo "Failed to sign the blob"; exit 1; }
+        shell: bash
+        env:
+          COSIGN_KEY: ${{secrets.Cosign_Key}}
+          COSIGN_PASSWORD: ${{secrets.Cosign_Key_Password}}
+
+      - name: Push Signed SBOM to Registry
+        run: |
+          set -e  # Exit on error
+          docker push ghcr.io/saurav631/sbom.json
+
       - name: Fetch commit details
         run: |
           # Get the commit ID
