Update maven-build.yml

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -332,21 +332,21 @@ jobs:
       - name: Sign SBOM
         run: |
           # set -e  # Exit on error
-          cosign sign-blob --yes --key env://COSIGN_KEY sbom.json 2>&1 #| jq -r .payload | base64 --decode | jq . 2>&1 #|| { echo "Failed to sign the blob"; exit 1; }
+          cosign sign-blob --yes --key env://COSIGN_KEY sbom.json --bundle cosign.bundle 2>&1 #| jq -r .payload | base64 --decode | jq . 2>&1 #|| { echo "Failed to sign the blob"; exit 1; }
         shell: bash
         env:
           COSIGN_KEY: ${{secrets.Cosign_Key}}
           COSIGN_PASSWORD: ${{secrets.Cosign_Key_Password}}
 
-      - name: Push Signed SBOM to Registry
-        run: |
-          # set -e  # Exit on error
-          docker push ghcr.io/saurav631/sbom.json
+      # - name: Push Signed SBOM to Registry
+      #   run: |
+      #     # set -e  # Exit on error
+      #     docker push ghcr.io/saurav631/sbom.json
 
-      - name: upload SBOM to Github Registry
+      - name: upload Signed SBOM to Github Registry
         run: |
           # set -e  # Exit on error
-          output2=$(cosign upload blob -f sbom.json ghcr.io/saurav631/demo/sbom 2>&1) #| jq .) #|| { echo "Failed to upload the blob to the Registry"; exit 1; }
+          output2=$(cosign upload blob -f sbom.json ghcr.io/saurav631/spring-petclinic:latest 2>&1) #| jq .) #|| { echo "Failed to upload the blob to the Registry"; exit 1; }
           echo "output: $output2"
           sbom_file=$(echo "$output2" | grep -oP 'sha256-[\w\d]+') || { echo "Failed to extract SBOM filename"; exit 1; }
           # Set the extracted SHA as an environment variable
@@ -357,9 +357,9 @@ jobs:
       #     # set -e  # Exit on error
       #     curl -L ghcr.io/saurav631/demo/sbom.json/blobs/$SBOM_FILE
 
-      - name: Sign SBOM
-        run: |
-          cosign sign --yes --key env://COSIGN_KEY ghcr.io/saurav631/demo/sbom.json/$SBOM_FILE
+      # - name: Sign SBOM
+      #   run: |
+      #     cosign sign --yes --key env://COSIGN_KEY ghcr.io/saurav631/demo/sbom.json/$SBOM_FILE
 
       - name: Fetch commit details
         run: |
