Update maven-build.yml

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -346,9 +346,9 @@ jobs:
       - name: upload Signed SBOM to Github Registry
         run: |
           # set -e  # Exit on error
-          output2=$(cosign upload blob -f sbom.json ghcr.io/saurav631/spring-petclinic:latest 2>&1) #| jq .) #|| { echo "Failed to upload the blob to the Registry"; exit 1; }
+          output2=$(cosign upload blob -f cosign.bundle ghcr.io/saurav631/spring-petclinic:latest 2>&1) #| jq .) #|| { echo "Failed to upload the blob to the Registry"; exit 1; }
           echo "output: $output2"
-          sbom_file=$(echo "$output2" | grep -oP 'sha256-[\w\d]+') || { echo "Failed to extract SBOM filename"; exit 1; }
+          sbom_file=$(echo "$output2" | grep -oP 'sha256:[\w\d]+') || { echo "Failed to extract SBOM filename"; exit 1; }
           # Set the extracted SHA as an environment variable
           echo "SBOM_FILE=$sbom_file" >> $GITHUB_ENV
 
